prolog-projection
   projectionFor
   releaseProjection
   updateProjection
prolog-base
   baseRelation
   addFact
   removeFact
prolog-derived
   derivedRelation
prolog-update-scheme
   visualizeIncrementalUpdateScheme
prolog-index
   indexOn
prolog-index-instance
   refIndexInstance
   releaseIndexInstance
-----
initialize ::= function () {
}
