dedb-projection
   projectionFor
   releaseProjection
   updateProjection
dedb-base
   baseRelation
   addFact
   removeFact
dedb-derived
   derivedRelation
dedb-join-plan
   visualizeIncrementalUpdateScheme
dedb-index
   indexOn
dedb-index-instance
   refIndexInstance
   releaseIndexInstance
-----
initialize ::= function () {
}
